# Generated by Django 6.0.2 on 2026-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_banner_description_ar_banner_description_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category_ar",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_en",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_ru",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category_uz",
        ),
        migrations.AddField(
            model_name="category",
            name="name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
