# Generated by Django 6.0.2 on 2026-02-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_product_category_ar_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
