# Generated by Django 6.0.2 on 2026-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_delete_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
