# Generated by Django 6.0.2 on 2026-02-14 07:59

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_product_is_available"),
    ]

    operations = [
        TrigramExtension(),
    ]
