# Generated by Django 6.0.2 on 2026-02-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_auto_20260214_1259"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.TextField(blank=True, null=True)),
                ("statistics", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="aboutus/"),
                ),
                (
                    "employer_image",
                    models.ImageField(blank=True, null=True, upload_to="aboutus/"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
