# Generated by Django 6.0.2 on 2026-02-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_aboutus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="statistics",
        ),
        migrations.AddField(
            model_name="aboutus",
            name="statistics",
            field=models.ManyToManyField(blank=True, null=True, to="base.statistics"),
        ),
    ]
