# Generated by Django 6.0.2 on 2026-02-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="statistics",
            options={"ordering": ("-created_at",)},
        ),
    ]
