# Generated by Django 6.0.2 on 2026-02-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_aboutus_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="subtitle_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="subtitle_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="subtitle_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aboutus",
            name="subtitle_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statistics",
            name="name_ar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="statistics",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="statistics",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="statistics",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
