# Generated by Django 6.0.2 on 2026-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_aboutus_description_ar_aboutus_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="banner/"),
        ),
    ]
